<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="NZNCGUVCPXQM2UF" ignored="0" name="Test" tests="8" failures="5" timestamp="2020-01-07T00:30:13 CST" time="0.055" errors="0">
  <testcase name="testAssert1" time="0.007" classname="test.Test15"/>
  <testcase name="testAssert1" time="0.001" classname="test.Test15">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at test.Test15.testAssert1(Test15.java:26)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testAssert1 -->
  <testcase name="testAssert2" time="0.001" classname="test.Test15"/>
  <testcase name="testAssert3" time="0.0" classname="test.Test15"/>
  <testcase name="testAssert4" time="0.001" classname="test.Test15">
    <failure type="java.lang.AssertionError" message="expected [6] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [2]
at test.Test15.testAssert4(Test15.java:39)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testAssert4 -->
  <testcase name="testAssert5" time="0.001" classname="test.Test15">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at test.Test15.testAssert5(Test15.java:44)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testAssert5 -->
  <testcase name="testAssert5" time="0.001" classname="test.Test15">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at test.Test15.testAssert5(Test15.java:44)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testAssert5 -->
  <testcase name="testAssert5" time="0.0" classname="test.Test15">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at test.Test15.testAssert5(Test15.java:44)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testAssert5 -->
</testsuite> <!-- Test -->
